package Vista;

/**
 *
 * @author jimen
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jm_agregarTipoProfesion = new javax.swing.JMenuItem();
        jm_eliminarTipoProfesion = new javax.swing.JMenuItem();
        jm_actualizarTipoProfesion = new javax.swing.JMenuItem();
        jm_listarTipoProfesion = new javax.swing.JMenuItem();
        jmenu_4 = new javax.swing.JMenu();
        jm_agregarMedico = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jm_Salir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenu3.setText("Tipo Profesion");

        jm_agregarTipoProfesion.setText("Agregar");
        jm_agregarTipoProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_agregarTipoProfesionActionPerformed(evt);
            }
        });
        jMenu3.add(jm_agregarTipoProfesion);

        jm_eliminarTipoProfesion.setText("Eliminar");
        jm_eliminarTipoProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_eliminarTipoProfesionActionPerformed(evt);
            }
        });
        jMenu3.add(jm_eliminarTipoProfesion);

        jm_actualizarTipoProfesion.setText("Actualizar");
        jm_actualizarTipoProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_actualizarTipoProfesionActionPerformed(evt);
            }
        });
        jMenu3.add(jm_actualizarTipoProfesion);

        jm_listarTipoProfesion.setText("Listar");
        jm_listarTipoProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_listarTipoProfesionActionPerformed(evt);
            }
        });
        jMenu3.add(jm_listarTipoProfesion);

        jMenu1.add(jMenu3);

        jmenu_4.setText("Medico");

        jm_agregarMedico.setText("Agregar Medico");
        jm_agregarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_agregarMedicoActionPerformed(evt);
            }
        });
        jmenu_4.add(jm_agregarMedico);

        jMenuItem2.setText("Eliminar Medico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmenu_4.add(jMenuItem2);

        jMenuItem7.setText("Actualizar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jmenu_4.add(jMenuItem7);

        jMenu1.add(jmenu_4);

        jMenu2.setText("Paciente");

        jMenuItem3.setText("Agregar");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Eliminar");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Actualizar");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Listar");
        jMenu2.add(jMenuItem6);

        jMenu1.add(jMenu2);

        jMenuBar1.add(jMenu1);

        jm_Salir.setText("Salir");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jm_Salir.add(jMenuItem1);

        jMenuBar1.add(jm_Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jm_agregarTipoProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_agregarTipoProfesionActionPerformed
        // TODO add your handling code here:
        Form_IngregarTipoProfesion itp = new Form_IngregarTipoProfesion();
        itp.setVisible(true);
        
        
    }//GEN-LAST:event_jm_agregarTipoProfesionActionPerformed

    private void jm_agregarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_agregarMedicoActionPerformed
        // TODO add your handling code here:
        Form_IngresarMedico fim = new Form_IngresarMedico();
        fim.setVisible(true);
    }//GEN-LAST:event_jm_agregarMedicoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Form_EliminarMedico fem = new Form_EliminarMedico();
        fem.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jm_eliminarTipoProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_eliminarTipoProfesionActionPerformed
        // TODO add your handling code here:
        Form_EliminarTipoProfesion fet = new Form_EliminarTipoProfesion();
        fet.setVisible(true);
    }//GEN-LAST:event_jm_eliminarTipoProfesionActionPerformed

    private void jm_actualizarTipoProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_actualizarTipoProfesionActionPerformed
        // TODO add your handling code here:
        Form_ActualizarTipoProfesion fat = new Form_ActualizarTipoProfesion();
        fat.setVisible(true);
    }//GEN-LAST:event_jm_actualizarTipoProfesionActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Form_ActMedico fam = new Form_ActMedico();
        fam.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jm_listarTipoProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_listarTipoProfesionActionPerformed
        // TODO add your handling code here:
        Form_listarProfesion flp = new Form_listarProfesion();
        flp.setVisible(true);
    }//GEN-LAST:event_jm_listarTipoProfesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jm_Salir;
    private javax.swing.JMenuItem jm_actualizarTipoProfesion;
    private javax.swing.JMenuItem jm_agregarMedico;
    private javax.swing.JMenuItem jm_agregarTipoProfesion;
    private javax.swing.JMenuItem jm_eliminarTipoProfesion;
    private javax.swing.JMenuItem jm_listarTipoProfesion;
    private javax.swing.JMenu jmenu_4;
    // End of variables declaration//GEN-END:variables
}
